### ISSUE TITLE
exmaple TOML config

### ISSUE THREAD

**Issue by damnatioMemorae** [rigormorrtiss/discordo#456]
i dont really know TOML syntax, and also dont know Golang. I have problems with my toml config. It would be nice to get some help and also if there was an example toml config file in the repo

**Comment by ayn2op** [comment]
Default configuration (may change in future):
```toml
mouse = true
hide_blocked_users = true
messages_limit = 50
editor = "default"
timestamps = false
timestamps_format = "3:04PM"
show_attachment_links = true

[keys]
  focus_guilds_tree = "Ctrl+G"
  focus_messages_text = "Ctrl+T"
  focus_message_input = "Ctrl+P"
  toggle_guilds_tree = "Ctrl+B"
  select_previous = "Rune[k]"
  select_next = "Rune[j]"
  select_first = "Rune[g]"
  select_last = "Rune[G]"
  logout = "Ctrl+D"
  quit = "Ctrl+C"
  [keys.guilds_tree]
    select_current = "Enter"
  [keys.messages_text]
    select_reply = "Rune[s]"
    select_pin = "Rune[p]"
    reply = "Rune[r]"
    reply_mention = "Rune[R]"
    delete = "Rune[d]"
    yank = "Rune[y]"
    open = "Rune[o]"
  [keys.message_input]
    send = "Enter"
    editor = "Ctrl+E"
    cancel = "Esc"

[theme]
  border = true
  border_color = "default"
  border_padding = [0, 0, 1, 1]
  title_color = "default"
  background_color = "default"
  [theme.guilds_tree]
    auto_expand_folders = true
    channel_color = "white"
    graphics = true
    guild_color = "white"
    private_channel_color = "white"
  [theme.messages_text]
    reply_indicator = "╭ "
    author_color = "aqua"
    content_color = "white"
    emoji_color = "green"
    link_color = "blue"
    attachment_color = "yellow"
```
