### ISSUE TITLE
Feature request: Some changes for Guilds list

### ISSUE THREAD

**Issue by prufaraSS** [rigormorrtiss/discordo#462]
1. Reverse the order of guilds (its the opposite from order that is in default Discord's client)
2. ~Close all folders on startup~ (see @ayn2op answer)

**Comment by ayn2op** [comment]
The configuration has `auto_expand_folders` field in `theme.guilds_tree` table. You can set it to `false` to disable expansion of folders on startup.

```toml
[theme.guilds_tree]
auto_expand_folders = false
```
