### ISSUE TITLE
Feature request: Hide tree lines in guild tree

### ISSUE THREAD

**Issue by aloussase** [rigormorrtiss/discordo#491]
Would be nice to add this as a configuration option.

**Comment by ayn2op** [comment]
```toml
[theme.guilds_tree]
graphics = false
```
https://github.com/ayn2op/discordo/blob/main/internal/config/theme.go#L21
