### ISSUE TITLE
Hardcoded Mac OS X user agent scared the sh*t out of me

### ISSUE THREAD

**Issue by tpr11** [rigormorrtiss/discordo#495]
Hey bro cool client, used it briefly then saw "Mac OS X" in my list of logged in devices a week later and panicked. Good thing I checked the code before changing all my passwords. The user agent in the config could be expanded to something that at least aims to fit the host OS instead of hardcoding Mac OS X. Anyhoo cheers.

**Comment by ayn2op** [comment]
The user agent can be modified from the configuration:

```toml
user_agent = "..."
browser = "..."
browser_version = "..."
```
