### ISSUE TITLE
Ensure arrows work the same as hjkl

### ISSUE THREAD

**Issue by fibsussy** [rigormorrtiss/discordo#524]
I still subscribe to vim ideologies by using hjkl to do movements on the homerow, its just I use a keyboard layer to switch hjkl to arrows. that way I can use hjkl anywhere in my system; not just in vim etc. Browsers use arrows, discord app uses arrows.... 

a lot of the qmk zmk etc programmable keyboards can have these type of homerow mods, along with that arrows should work anyway therye doing nothing atm

so just make sure to implement arrows!

**Comment by ayn2op** [comment]
You can customize the navigation keys using the [configuration file](https://github.com/ayn2op/discordo#configuration):
```toml
[keys.guilds_tree]
select_previous = "Up"
select_next = "Down"
select_first = "Home"
select_last = "End"

[keys.messages_text]
select_previous = "Up"
select_next = "Down"
select_first = "Home"
select_last = "End"
```

**Comment by pancsta** [comment]
Basic feature is not a customization. I wont even mention tab navigation and focus stealing...

```toml
[keys.guilds_tree]
select_previous = "Up"
select_next = "Down"
select_first = "Home"
select_last = "End"

[keys.messages_text]
select_previous = "Up"
select_next = "Down"
select_first = "Home"
select_last = "End"
```

Doesnt work.
