### ISSUE TITLE
Timestamps option results in error

### ISSUE THREAD

**Issue by Perchaway** [rigormorrtiss/discordo#532]
Since the latest update I get the following error when having the timestamp setting set to true in config:
"Error: toml: line 2 (last key "timestamps"): type mismatch for config.Timestamps: expected table but found bool"

Any new option I need to add in config?

**Comment by ayn2op** [comment]
```toml
timestamps = true
timestamps_format = "X"
```
to
```toml
[timestamps]
enabled = true
format = "X"
```
